services:
  postgres:
    image: postgres:17-alpine
    container_name: crudproductos_postgres
    restart: unless-stopped
    user: '70:70'
    environment:
      POSTGRES_DB: crudproductos_db
      POSTGRES_USER: jef
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_INITDB_ARGS: '--auth-host=scram-sha-256 --auth-local=scram-sha-256'
      PGDATA: /var/lib/postgresql/data/pgdata
    secrets:
      - postgres_password
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -h 127.0.0.1 -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /var/run/postgresql:uid=70,gid=70,mode=3775
    networks:
      - backend

volumes:
  postgres_data:
    name: crudproductos_postgres_data

secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  backend:
    name: crudproductos_backend
    driver: bridge
