-- Limpiar la tabla y reiniciar el ID
TRUNCATE TABLE "Productos" RESTART IDENTITY;

-- Insertar productos de prueba
INSERT INTO "Productos" ("Nombre", "Descripcion", "Precio", "Stock", "FechaRegistro") VALUES
('Laptop Lenovo ThinkPad E14', 'Laptop empresarial para desarrollo y oficina', 850.00, 12, NOW()),
('Laptop HP Pavilion 15', 'Equipo portátil para estudiantes universitarios', 720.50, 8, NOW()),
('Laptop Dell Inspiron 14', 'Laptop de uso académico y administrativo', 690.00, 5, NOW()),
('MacBook Air M2', 'Laptop ultraligera para diseño y programación', 1250.00, 3, NOW()),
('Monitor Samsung 24 pulgadas', 'Monitor Full HD para oficina y laboratorio', 180.00, 15, NOW()),
('Monitor LG UltraWide 29 pulgadas', 'Monitor panorámico para productividad', 320.00, 6, NOW()),
('Teclado Logitech K120', 'Teclado USB básico para laboratorio', 14.99, 40, NOW()),
('Teclado Mecánico Redragon Kumara', 'Teclado mecánico para programación y gaming', 55.00, 10, NOW()),
('Mouse Logitech M170', 'Mouse inalámbrico compacto', 12.50, 35, NOW()),
('Mouse Gamer Razer DeathAdder', 'Mouse ergonómico de alta precisión', 65.00, 7, NOW()),
('Disco SSD Kingston 480GB', 'Unidad de estado sólido SATA para computadoras', 42.00, 20, NOW()),
('Disco SSD NVMe Samsung 1TB', 'Unidad NVMe de alto rendimiento', 110.00, 9, NOW()),
('Memoria RAM Kingston 8GB DDR4', 'Memoria RAM para equipos de escritorio', 35.00, 25, NOW()),
('Memoria RAM Corsair 16GB DDR4', 'Memoria RAM para estaciones de trabajo', 72.00, 11, NOW()),
('Router TP-Link Archer C6', 'Router inalámbrico dual band para red local', 48.00, 13, NOW()),
('Switch TP-Link 8 puertos', 'Switch de red para laboratorio', 28.50, 18, NOW()),
('Cable HDMI 2 metros', 'Cable HDMI para proyector o monitor', 8.00, 60, NOW()),
('Cable de red Cat6 3 metros', 'Cable Ethernet para conexión LAN', 4.50, 75, NOW()),
('Impresora Epson EcoTank L3250', 'Impresora multifuncional con sistema continuo', 235.00, 4, NOW()),
('Impresora HP LaserJet Pro', 'Impresora láser para oficina', 290.00, 2, NOW()),
('Webcam Logitech C920', 'Cámara web Full HD para clases virtuales', 89.00, 6, NOW()),
('Micrófono Fifine USB', 'Micrófono para grabación de clases y reuniones', 49.00, 9, NOW()),
('Audífonos JBL Tune 510BT', 'Audífonos inalámbricos para uso diario', 45.00, 14, NOW()),
('Parlantes Genius USB', 'Parlantes compactos para computador', 18.00, 22, NOW()),
('Tablet Samsung Galaxy Tab A9', 'Tablet para lectura, clases y navegación', 210.00, 5, NOW()),
('Proyector Epson X49', 'Proyector para aula y presentaciones', 620.00, 1, NOW()),
('UPS Forza 1000VA', 'Sistema de respaldo eléctrico para equipos', 95.00, 7, NOW()),
('Regulador de voltaje CDP', 'Protección eléctrica para computadoras', 28.00, 16, NOW()),
('Licencia Antivirus ESET', 'Licencia anual de seguridad informática', 32.00, 30, NOW()),
('Licencia Microsoft 365 Personal', 'Suscripción para herramientas de oficina', 69.00, 12, NOW()),
('Silla ergonómica ejecutiva', 'Silla para oficina con soporte lumbar', 145.00, 6, NOW()),
('Escritorio metálico moderno', 'Escritorio para laboratorio o aula', 180.00, 4, NOW()),
('Pizarra acrílica 120x80', 'Pizarra blanca para clases', 55.00, 8, NOW()),
('Marcadores borrables paquete x4', 'Marcadores para pizarra acrílica', 6.50, 50, NOW()),
('Pendrive Kingston 64GB', 'Unidad USB para respaldo de archivos', 9.50, 45, NOW()),
('Disco externo Seagate 2TB', 'Disco duro externo para copias de seguridad', 88.00, 10, NOW()),
('Adaptador USB-C a HDMI', 'Adaptador para conectar laptop a monitor', 18.00, 17, NOW()),
('Hub USB 4 puertos', 'Concentrador USB para periféricos', 15.00, 21, NOW()),
('Cargador universal para laptop', 'Cargador compatible con varios modelos', 38.00, 9, NOW()),
('Soporte para laptop ajustable', 'Base ergonómica para laptop', 24.00, 19, NOW());