TRUNCATE TABLE "Productos" RESTART IDENTITY;
TRUNCATE TABLE "Categorias" RESTART IDENTITY CASCADE;

INSERT INTO "Categorias" ("Nombre", "Descripcion", "DescuentoPorcentaje", "Activa", "FechaCreacion") VALUES
('Computadoras', 'Equipos portatiles y de escritorio para laboratorio', 5.00, TRUE, NOW()),
('Monitores', 'Pantallas para oficina, aula y productividad', 7.50, TRUE, NOW()),
('Perifericos', 'Teclados, mouse, webcam y accesorios USB', 10.00, TRUE, NOW()),
('Almacenamiento', 'Discos SSD, NVMe, externos y unidades USB', 8.00, TRUE, NOW()),
('Redes', 'Routers, switches y cableado de red', 6.00, TRUE, NOW()),
('Impresion', 'Impresoras laser, tinta y consumibles', 4.50, TRUE, NOW()),
('Software', 'Licencias, suscripciones y seguridad informatica', 12.00, TRUE, NOW()),
('Mobiliario', 'Sillas, escritorios y elementos para aula', 3.00, FALSE, NOW());

INSERT INTO "Productos" ("Nombre", "Descripcion", "Precio", "Stock", "CategoriaId", "FechaRegistro") VALUES
('Laptop Lenovo ThinkPad E14', 'Laptop empresarial para desarrollo y oficina', 850.00, 12, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Computadoras'), NOW()),
('Laptop HP Pavilion 15', 'Equipo portatil para estudiantes universitarios', 720.50, 8, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Computadoras'), NOW()),
('Laptop Dell Inspiron 14', 'Laptop de uso academico y administrativo', 690.00, 5, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Computadoras'), NOW()),
('MacBook Air M2', 'Laptop ultraligera para diseno y programacion', 1250.00, 3, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Computadoras'), NOW()),
('Monitor Samsung 24 pulgadas', 'Monitor Full HD para oficina y laboratorio', 180.00, 15, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Monitores'), NOW()),
('Monitor LG UltraWide 29 pulgadas', 'Monitor panoramico para productividad', 320.00, 6, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Monitores'), NOW()),
('Teclado Logitech K120', 'Teclado USB basico para laboratorio', 14.99, 40, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Teclado Mecanico Redragon Kumara', 'Teclado mecanico para programacion y gaming', 55.00, 10, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Mouse Logitech M170', 'Mouse inalambrico compacto', 12.50, 35, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Mouse Gamer Razer DeathAdder', 'Mouse ergonomico de alta precision', 65.00, 7, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Disco SSD Kingston 480GB', 'Unidad de estado solido SATA para computadoras', 42.00, 20, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Disco SSD NVMe Samsung 1TB', 'Unidad NVMe de alto rendimiento', 110.00, 9, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Memoria RAM Kingston 8GB DDR4', 'Memoria RAM para equipos de escritorio', 35.00, 25, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Memoria RAM Corsair 16GB DDR4', 'Memoria RAM para estaciones de trabajo', 72.00, 11, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Router TP-Link Archer C6', 'Router inalambrico dual band para red local', 48.00, 13, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Redes'), NOW()),
('Switch TP-Link 8 puertos', 'Switch de red para laboratorio', 28.50, 18, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Redes'), NOW()),
('Cable HDMI 2 metros', 'Cable HDMI para proyector o monitor', 8.00, 60, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Monitores'), NOW()),
('Cable de red Cat6 3 metros', 'Cable Ethernet para conexion LAN', 4.50, 75, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Redes'), NOW()),
('Impresora Epson EcoTank L3250', 'Impresora multifuncional con sistema continuo', 235.00, 4, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Impresion'), NOW()),
('Impresora HP LaserJet Pro', 'Impresora laser para oficina', 290.00, 2, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Impresion'), NOW()),
('Webcam Logitech C920', 'Camara web Full HD para clases virtuales', 89.00, 6, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Microfono Fifine USB', 'Microfono para grabacion de clases y reuniones', 49.00, 9, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Audifonos JBL Tune 510BT', 'Audifonos inalambricos para uso diario', 45.00, 14, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Parlantes Genius USB', 'Parlantes compactos para computador', 18.00, 22, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Tablet Samsung Galaxy Tab A9', 'Tablet para lectura, clases y navegacion', 210.00, 5, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Computadoras'), NOW()),
('Proyector Epson X49', 'Proyector para aula y presentaciones', 620.00, 1, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Monitores'), NOW()),
('UPS Forza 1000VA', 'Sistema de respaldo electrico para equipos', 95.00, 7, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Regulador de voltaje CDP', 'Proteccion electrica para computadoras', 28.00, 16, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Licencia Antivirus ESET', 'Licencia anual de seguridad informatica', 32.00, 30, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Software'), NOW()),
('Licencia Microsoft 365 Personal', 'Suscripcion para herramientas de oficina', 69.00, 12, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Software'), NOW()),
('Silla ergonomica ejecutiva', 'Silla para oficina con soporte lumbar', 145.00, 6, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Escritorio metalico moderno', 'Escritorio para laboratorio o aula', 180.00, 4, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Pizarra acrilica 120x80', 'Pizarra blanca para clases', 55.00, 8, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Marcadores borrables paquete x4', 'Marcadores para pizarra acrilica', 6.50, 50, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Mobiliario'), NOW()),
('Pendrive Kingston 64GB', 'Unidad USB para respaldo de archivos', 9.50, 45, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Disco externo Seagate 2TB', 'Disco duro externo para copias de seguridad', 88.00, 10, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Almacenamiento'), NOW()),
('Adaptador USB-C a HDMI', 'Adaptador para conectar laptop a monitor', 18.00, 17, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Hub USB 4 puertos', 'Concentrador USB para perifericos', 15.00, 21, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Cargador universal para laptop', 'Cargador compatible con varios modelos', 38.00, 9, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW()),
('Soporte para laptop ajustable', 'Base ergonomica para laptop', 24.00, 19, (SELECT "Id" FROM "Categorias" WHERE "Nombre" = 'Perifericos'), NOW());
