DROP TABLE IF EXISTS "Productos";
DROP TABLE IF EXISTS "Categorias";

CREATE TABLE "Categorias" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(80) NOT NULL,
    "Descripcion" VARCHAR(200) NOT NULL,
    "DescuentoPorcentaje" NUMERIC(5, 2) NOT NULL DEFAULT 0,
    "Activa" BOOLEAN NOT NULL DEFAULT TRUE,
    "FechaCreacion" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE "Productos" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Nombre" VARCHAR(100) NOT NULL,
    "Descripcion" VARCHAR(250) NOT NULL,
    "Precio" NUMERIC NOT NULL,
    "Stock" INTEGER NOT NULL,
    "CategoriaId" INTEGER NULL,
    "FechaRegistro" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT "FK_Productos_Categorias_CategoriaId"
        FOREIGN KEY ("CategoriaId")
        REFERENCES "Categorias" ("Id")
        ON DELETE SET NULL
);

CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");
